### ISSUE TITLE
bodyにCSSが適用されてない

### ISSUE THREAD

**Issue by bamboosteam** [bamboosteam/sb-fy20-pbl-it-operation#168]
- details.html
- index.html
- insertContentsConfirm.html
- insertContentsComplete.html
- insertComplete.html
- insert.html
- insertMenu.html
- insertNext.html
- insertQualificationComplete.html
- insertQualificationConfirm.html
- insertSectionComplete.html
- insertSectionConfirm.html
- insertSectionContens.html
- insertTextComplete.html
- insertTextConfirm.html
- mypage.html
- sectionContents.html

**Comment by pipKotaro** [comment]
<適応済>
details.html
sectionContents.html
