### ISSUE TITLE
プラットフォーム開発課を押すとエラーが出る

### ISSUE THREAD

**Issue by SassaH** [bamboosteam/sb-fy20-pbl-it-operation#308]
エラー画面
### Error querying database. Cause: com.microsoft.sqlserver.jdbc.SQLServerException: Subquery returned more than 1 value. This is not permitted when the subquery follows =, !=, <, <= , >, >= or when the subquery is used as an expression. ### The error may exist in com/example/demo/persistence/mapper/SectionContentsMapper.java (best guess) ### The error may involve com.example.demo.persistence.mapper.SectionContentsMapper.findBySectionLike ### The error occurred while handling results ### SQL: SELECT s.name AS section_name, c.name AS contents_name, sc.comment AS section_contents_comment FROM contents_list AS c JOIN section_contents AS sc ON sc.contents_id = c.id JOIN section AS s ON sc.section_id = s.id WHERE s.id = (SELECT id FROM section WHERE name LIKE ?) ORDER BY s.id ### Cause: com.microsoft.sqlserver.jdbc.SQLServerException: Subquery returned more than 1 value. This is not permitted when the subquery follows =, !=, <, <= , >, >= or when the subquery is used as an expression. ; uncategorized SQLException; SQL state [S0001]; error code [512]; Subquery returned more than 1 value. This is not permitted when the subquery follows =, !=, <, <= , >, >= or when the subquery is used as an expression.; nested exception is com.microsoft.sqlserver.jdbc.SQLServerException: Subquery returned more than 1 value. This is not permitted when the subquery follows =, !=, <, <= , >, >= or when the subquery is used as an expression.

**Comment by YuyaKurashige** [comment]
修正しました
